Api/Models/ErrorViewModel.cs
namespace Api.Models;

public record ErrorViewModel(string RequestId, string ErrorMessage)
{
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Api/Models/GithubViewModel.cs
using Api.Dtos;

namespace Api.Models;

public class GithubViewModel
{
    public GithubViewModel(string userName, IReadOnlyList<RepositoryDto> repositories)
    {
        UserName = userName;
        Repositories = repositories;
    }

    public string UserName { get; set; }
    public IReadOnlyList<RepositoryDto> Repositories { get; set; }
}

Api/Controllers/FavoriteController.cs
using Api.Dtos;
using Api.Models;
using Api.Services;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers;

public class FavoriteController : Controller
{
    private readonly IGithubServices _githubServices;
    private readonly IFavoriteServices _favoriteServices;
    private readonly IConfiguration _configuration;

    public FavoriteController(IGithubServices githubServices, IConfiguration configuration, IFavoriteServices favoriteServices)
    {
        _githubServices = githubServices;
        _configuration = configuration;
        _favoriteServices = favoriteServices;
    }

    public async Task<IActionResult> Index()
    {
        IList<RepositoryDto> repositories = new List<RepositoryDto>();

        await Task.Run(async () =>
        {
            foreach (var repoName in _favoriteServices.Favorites)
            {
                var repo = await _githubServices.GetRepositoryFromRepoName(repoName);
                repositories.Add(repo);
            }
        });

        ViewBag.favorites = _favoriteServices.Favorites;
        var model = new GithubViewModel(_configuration["GithubMainUser"], repositories.ToList().AsReadOnly());
        return View(model);
    }

    [HttpPost]
    public IActionResult Like(string repoName)
    {
        _favoriteServices.AddRepository(repoName);
        return Json("success!");
    }
}

Api/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Api/Controllers/MyRepositoriesController.cs
using Api.Models;
using Api.Services;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers;

public class MyRepositoriesController : Controller
{
    private readonly IGithubServices _githubServices;
    private readonly IFavoriteServices _favoriteServices;
    private readonly IConfiguration _configuration;

    public MyRepositoriesController(IGithubServices githubServices, IConfiguration configuration, IFavoriteServices favoriteServices)
    {
        _githubServices = githubServices;
        _configuration = configuration;
        _favoriteServices = favoriteServices;
    }

    public async Task<IActionResult> Index()
    {
        var repositories = await _githubServices.GetAllRepositoriesFromUser(_configuration["GithubMainUser"]);
        var model = new GithubViewModel(_configuration["GithubMainUser"], repositories);

        ViewBag.favorites = _favoriteServices.Favorites;
        return View(model);
    }

    [HttpPost]
    public IActionResult Like(string repoName)
    {
        _favoriteServices.AddRepository(repoName);
        return Json("success!");
    }

    public IActionResult OnPostNavigate()
    {
        string dataToSend = "Hello from the source page!";
        return RedirectToPage("/TargetPage", new { data = dataToSend });
    }
}

Api/Controllers/OtherRepositoriesController.cs
using Api.Dtos;
using Api.Models;
using Api.Services;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers;
public class OtherRepositoriesController : Controller
{
    private readonly IGithubServices _githubServices;

    public OtherRepositoriesController(IGithubServices githubServices)
    {
        _githubServices = githubServices;
    }

    public IActionResult Index()
    {
        return View(new GithubViewModel("Enter a repository name", new List<RepositoryDto>()));
    }

    [HttpGet]
    public async Task<IActionResult> Search(string value)
    {
        var repositories = await _githubServices.GetAllRepositoriesFromRepoName(value);
        return Json(new GithubViewModel(value, repositories));
    }
}

Api/Controllers/RepositoryDetailController.cs
using Api.Services;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers;

public class RepositoryDetailController : Controller
{

    private readonly IFavoriteServices _favoriteServices;
    private readonly IGithubServices _githubServices;

    public RepositoryDetailController(IFavoriteServices favoriteServices, IGithubServices githubServices)
    {
        _favoriteServices = favoriteServices;
        _githubServices = githubServices;
    }

    public async Task<IActionResult> Index(string name)
    {
        ViewBag.favorites = _favoriteServices.Favorites;
        var repo = await _githubServices.GetRepositoryFromRepoName(name);
        return View(repo);
    }

    [HttpPost]
    public IActionResult Like(string repoName)
    {
        _favoriteServices.AddRepository(repoName);
        return Json("success!");
    }
}

Api/Views/Favorite/Index.cshtml
@model GithubViewModel

<!DOCTYPE html>
<html>
<head>
    <title>My Favorites</title>
    <link rel="stylesheet" href="~/css/repositories.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.likeButton').click(function () {
                $(this).toggleClass('liked');
                var isLiked = $(this).hasClass('liked');
                this.innerText = isLiked ? "DESLIKE" : "LIKE";
                var repo = $(this).data('repo');
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Like", "MyRepositories")',
                    data: { repoName: repo },
                    success: function (data) {
                        console.log(repo);
                    },
                    error: function (error) {
                        console.error(error);
                    }
                });
            });
        });
    </script>
</head>
<body>
    <div class="center-div">
        <ul>
            @foreach (var repo in Model.Repositories)
            {
                <li data-repo-name="@repo.Name" class="repo-item">
                    <div class="repo-container">
                        <a href="@repo.Url" target="_blank">
                            <h2>@repo.Name</h2>
                            <div>
                                <h4 class="d-inline">Language: </h4>
                                <b><span>@repo.Language</span></b>
                            </div>
                            <h4>Description:</h4>
                            <p>@repo.Description</p>
                        </a>
                        <button class="likeButton liked" data-repo="@repo.Name">
                            <text>DESLIKE</text>
                        </button>
                    </div>
                </li>
            }
        </ul>
    </div>
</body>
</html>

Api/Views/Home/Index.cshtml
@model GithubViewModel

<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
    <link rel="stylesheet" href="~/css/home.css" />
</head>
<body>
    <div class="center-div">
        <ul class="navbar-nav home-navbar">
            <li class="nav-item">
                <div class="home-container">
                    <a class="nav-link text-dark" asp-area="" asp-controller="MyRepositories" asp-action="Index">
                        <h1>My Repositories</h1>
                    </a>
                </div>
            </li>
            <li class="nav-item">
                <div class="home-container">
                    <a class="nav-link text-dark" asp-area="" asp-controller="OtherRepositories" asp-action="Index">
                        <h1>Others Repositories</h1>
                    </a>
                </div>
            </li>
            <li class="nav-item">
                <div class="home-container">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Favorite" asp-action="Index">
                        <h1>Favorites</h1>
                    </a>
                </div>
            </li>
        </ul>
    </div>
</body>
</html>

Api/Views/MyRepositories/Index.cshtml
@using System.Text.Json
@model GithubViewModel

<!DOCTYPE html>
<html>
<head>
    <title>My Repositories</title>
    <link rel="stylesheet" href="~/css/repositories.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/myRepositories.js"></script>
    <script>
        $(document).ready(function () {
            $('.likeButton').click(function () {
                $(this).toggleClass('liked');
                this.innerText = this.innerText === "LIKE" ? "DESLIKE" : "LIKE";
                var repo = $(this).data('repo');
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Like", "MyRepositories")',
                    data: { repoName: repo },
                    success: function (data) {
                        console.log(repo);
                    },
                    error: function (error) {
                        console.error(error);
                    }
                });
            });
        });
    </script>
</head>
<body>
    <div class="center-div">
        <h1 class="display-4">@Model.UserName.ToUpper()</h1>
        <input id="repositoryNameInput" type="text" oninput="handleRepositoryNameInput()" value="Search for repository by name" />
        <ul>
            @foreach (var repo in Model.Repositories)
            {
                <li data-repo-name="@repo.Name" class="repo-item">
                    <div class="repo-container">
                        <div class="flex-row">
                            <a asp-controller="RepositoryDetail" asp-action="Index" asp-route-name="@repo.Name">
                                <h2>@repo.Name</h2>
                            </a>
                            @{
                                string buttonClass = ViewBag.favorites.Contains(repo.Name) ? "likeButton liked" : "likeButton";
                                string buttonName = ViewBag.favorites.Contains(repo.Name) ? "DESLIKE" : "LIKE";
                            }
                            <button class="@buttonClass" data-repo="@repo.Name">@buttonName</button>
                        </div>
                    </div>
                </li>
            }
        </ul>
    </div>
</body>
</html>

Api/Views/OtherRepositories/Index.cshtml
@model GithubViewModel

<!DOCTYPE html>
<html>
<head>
    <title>Others Repositories</title>
    <link rel="stylesheet" href="~/css/repositories.css" />
</head>
<body>
    <div class="center-div">
        <h1 class="display-4">Others Repositories</h1>
        @Html.TextBoxFor(_ => _.UserName, new { @oninput = "search(this.value);" })
        <div id="userRepositories"></div>
    </div>
</body>
</html>

<script type="text/javascript">
    function renderRepository(repo) {
        var li = document.createElement('li');
        li.setAttribute('data-repo-name', repo.name);
        li.className = 'repo-item';

        var a = document.createElement('a');
        a.href = repo.url;
        a.target = '_blank';

        var div = document.createElement('div');
        div.className = 'repo-container';

        var username = document.createElement('h2');
        username.textContent = 'Username: ' + repo.login;

        var h2 = document.createElement('h2');
        h2.textContent = repo.name;

        var languageDiv = document.createElement('div');
        var h4 = document.createElement('h4');
        h4.className = 'd-inline';
        h4.textContent = 'Language: ';
        var b = document.createElement('b');
        var span = document.createElement('span');
        span.textContent = repo.language;
        b.appendChild(span);
        languageDiv.appendChild(h4);
        languageDiv.appendChild(b);

        var descriptionH4 = document.createElement('h4');
        descriptionH4.textContent = 'Description:';

        var descriptionP = document.createElement('p');
        descriptionP.textContent = repo.description;

        div.appendChild(username);
        div.appendChild(h2);
        div.appendChild(languageDiv);
        div.appendChild(descriptionH4);
        div.appendChild(descriptionP);

        a.appendChild(div);
        li.appendChild(a);

        return li;
    }

    function search(value) {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("Search", "OtherRepositories")',
            data: { value: value },
            success: function (data) {
                console.log(data);
                var repositoriesList = document.getElementById('userRepositories');
                repositoriesList.innerHTML = '';

                for (var i = 0; i < data.repositories.length; i++) {
                    var repo = data.repositories[i];
                    var li = renderRepository(repo);
                    repositoriesList.appendChild(li);
                }
            },
            error: function (error) {
                console.error(error);
            }
        });
    }

    $(document).ready(function () {
        $('.likeButton').click(function () {
            $(this).toggleClass('liked');
            var repo = $(this).data('repo');
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Like", "MyRepositories")',
                data: { repoName: repo },
                success: function (data) {
                    console.log(repo);
                },
                error: function (error) {
                    console.error(error);
                }
            });
        });
    });
</script>

Api/Views/RepositoryDetail/Index.cshtml
@using Api.Dtos;
@model RepositoryDto

<!DOCTYPE html>
<html>
<head>
    <title>@Model.Name</title>
    <link rel="stylesheet" href="~/css/repositories.css" />
</head>
<body>
    <div class="center-div">
        <div class="repo-details">
            <a href="@Model.Url" target="_blank">
                <div>
                    <h4 class="d-inline">Language: <b><span>@Model.Language</span></b></h4>
                </div>
                <h4>Description:</h4>
                <p>@Model.Description</p>
                <h4>Last Updated:</h4>
                <p>@Model.LastUpdated.ToString("dd/MM/yyyy hh:mm")</p>
            </a>
        </div>
    </div>
</body>
</html>

Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Github WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Api.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom mb-4">
            <div class="container">
                <a class="navbar-brand" href="#">Github WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="MyRepositories" asp-action="Index">My Repositories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="OtherRepositories" asp-action="Index">Others Repositories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Favorite" asp-action="Index">Favorites</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Api - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>